#pragma once

#include <cstdint>
#include <tuple>
#include <type_traits>

#include "../dsl/jems.hpp"
#include "reference.hpp"
#include "reflection.hpp"
#include "static_string.hpp"
#include "static_access_chain.hpp"

template <typename T, size_t ... Is>
struct field_trace;

struct AutoGenerated;

// Injecting with a given reference
template <typename T>
struct injector {
	static void main(T &, Reference) {
		static_assert(false, ($ss("failed to inject reference into item of type ") + $ss_type(T)).view());
	}
};

template <typename T>
requires std::is_base_of_v <jems::handle, T>
struct injector <T> {
	static void main(T &item, Reference ref) {
		item.override_reference(ref);
	}
};

// Injecting a reference into a resource at a specific access chain
template <typename T, size_t ... Is>
struct injector <field_trace <T, Is...>> {
	template <auto &rsrc>
	static void main(reference <rsrc> &value, Reference ref) {
		static_access_chain <Is...> (value).override_reference(ref);
	}
};

template <typename ... Ts>
struct injector <aggregate_reflection <AutoGenerated, Ts...>> {
	template <auto &rsrc>
	static void main(reference <rsrc> &value, Reference ref) {
		uint32_t counter = 0;
		auto inject = [&](auto x) {
			auto access = jems::field_access(ref, counter++);
			injector <decltype(x)> ::main(value, access);
			return true;
		};

		std::apply([&](auto ... xs) {
			std::make_tuple(inject(xs)...);
		}, std::tuple <Ts...> ());
	}
};
