#pragma once

#include "reflection.hpp"
#include "resources.hpp"

struct AutoGenerated {};

// TODO: need to handle cases where its not immediately an aggregate?
template <typename A, typename B>
struct uniform_merge {
	using type = aggregate_reflection <AutoGenerated>;
};

template <typename ... Ts, typename B>
struct uniform_merge <aggregate_reflection <AutoGenerated, Ts...>, B> {
	using type = aggregate_reflection <AutoGenerated, Ts..., B>;
};

// <Uniform> holds all the uniform/push constant parts
// and <Resources...> are all the GRVs accumulated
template <typename Uniform, typename Resources, typename ... Ts>
struct parameter_block_filter {
	using uniform = std::conditional_t <
		std::same_as <Uniform, aggregate_reflection <AutoGenerated>>,
		void, Uniform
	>;

	using resources = Resources;

	using type = parameter_block_filter <uniform, resources>;
	// NOTE: only for debugging the metaprogramming
	using next = type;
};

template <typename Uniform, typename Resources, typename ... Ts>
using parameter_block_filter_t = parameter_block_filter <Uniform, Resources, Ts...> ::type;

// Top-level case, simply forward the interior of the parameter block
template <typename Uniform, typename Resources, typename T, size_t ... Is, typename ... Ts>
struct parameter_block_filter <
	Uniform,
	Resources,
	field_trace <parameter_block_reflection <T>, Is...>,
	Ts...
> {
	using next = parameter_block_filter <Uniform, Resources, field_trace <T, Is...>, Ts...>;
	using type = next::type;
};

// Default case, attempt to merge into the uniforms as an ordinary type
template <typename Uniform, typename Resources, typename T, typename ... Ts>
struct parameter_block_filter <Uniform, Resources, T, Ts...> {
	using merged = uniform_merge <Uniform, T> ::type;
	using next = parameter_block_filter <merged, Resources, Ts...>;
	using type = next::type;
};

// Resources are appended to the resource list
template <typename Uniform, typename Resources, typename T, size_t ... Is, typename ... Ts>
requires is_resource_reflection_v <T>
struct parameter_block_filter <Uniform, Resources, field_trace <T, Is...>, Ts...> {
	using resources = typename Resources::template push_back_t <field_trace <T, Is...>>;
	using next = parameter_block_filter <Uniform, resources, Ts...>;
	using type = next::type;
};

// For aggregates, we need to push an index into the field_traces
template <typename Uniform, typename Resources, typename T, size_t ... Is, typename ... TFields, typename ... Ts>
struct parameter_block_filter <
	Uniform,
	Resources,
	field_trace <aggregate_reflection <T, TFields...>, Is...>,
	Ts...
> {
	template <size_t ... Order>
	struct impl {
		using result = parameter_block_filter <
			Uniform,
			Resources,
			field_trace <TFields, Is..., Order>...,
			Ts...
		>;
	};

	template <size_t ... Order>
	static auto new_impl(std::index_sequence <Order...>) -> impl <Order...>;

	using impl_result = decltype(new_impl(std::index_sequence_for <TFields...> ()));

	using next = impl_result::result;
	using type = next::type;
};
