#pragma once

#include "reflection.hpp"
#include "scaffold.hpp"

// Building the reflection for aggregates
template <typename Original, typename ... Ts>
auto new_aggregate_reflection(sequence <Ts...>)
	-> aggregate_reflection <Original, Ts...>;

#define GEN_AGGREGATE_FIELD(T, field)	\
	std::declval <decltype(field)> (),

#define DEFINE_REFLECTION(...)							\
	using reflection = decltype(new_aggregate_reflection <This> (		\
		sequence {							\
			MAP(GEN_AGGREGATE_FIELD, /* NA */ , __VA_ARGS__)	\
		}								\
	));

// Mapping each field to a unique (local) index
#define GEN_AGGREGATE_FIELD_COUNTER(T, field)	\
	el <__COUNTER__ - counter_base - 1> field;
	
#define DEFINE_FIELDS(...)							\
	struct field_counter {							\
		static constexpr size_t counter_base = __COUNTER__;		\
		MAP(GEN_AGGREGATE_FIELD_COUNTER, This, __VA_ARGS__)		\
	};									\
	MAP(FIELD_NAME_INJECTION, This, __VA_ARGS__)				\

// Generating a tuple-like get method
#define GEN_AGGREGATE_FIELD_REFERENCE(T, field)	\
	else if constexpr (D == ((__COUNTER__ - 1) - counter_base)) { return field; }
	
#define DEFINE_FIELD_REFERENCE(R, ...)						\
	template <size_t D>							\
	auto &_ugp_field_reference() R {					\
		static constexpr size_t counter_base = __COUNTER__;		\
		if constexpr (false) {}						\
		MAP(GEN_AGGREGATE_FIELD_REFERENCE, /* NA */, __VA_ARGS__)	\
		else {								\
			static_assert(false,					\
		 		($ss("out of bounds field reference access of ")\
		 		+ $ss_type(This)).view());			\
			return _ugp_reference_default;				\
		}								\
	}									\

// Generating the override reference method
#define GEN_OVERRIDE_FIELD_REFERENCE(T, field)	\
	field.override_reference(jems::field_access(ref, __COUNTER__ - counter_base - 1));

#define DEFINE_OVERRIDE_REFERENCE(...)						\
	void override_reference(const Reference &ref) {				\
		static constexpr size_t counter_base = __COUNTER__;		\
		MAP(GEN_OVERRIDE_FIELD_REFERENCE, /* ... */, __VA_ARGS__)	\
	}									\

// Manual marker to indicate membership in the reflection system
#define DEFINE_REFLECTION_STAMP() static constexpr bool _ugp_has_reflection = true

// Full reflection information for aggregates
#define $reflection(...)					\
	DEFINE_THIS();						\
	DEFINE_REFLECTION_STAMP();				\
								\
	DEFINE_REFLECTION(__VA_ARGS__);				\
	DEFINE_FIELDS(__VA_ARGS__);				\
	DEFINE_SCAFFOLD(__VA_ARGS__);				\
								\
	static inline AutoGenerated _ugp_reference_default;	\
	DEFINE_FIELD_REFERENCE(/*&*/, __VA_ARGS__);		\
	DEFINE_FIELD_REFERENCE(const, __VA_ARGS__);		\
								\
	DEFINE_OVERRIDE_REFERENCE(__VA_ARGS__);			\
