#pragma once

#include <cstdint>
#include <tuple>
#include <type_traits>

#include "../dsl/jems.hpp"
#include "expand_reflection.hpp"
#include "injection_state.hpp"
#include "injector.hpp"
#include "parameter_block_filter.hpp"
#include "resource_intrinsic.hpp"
#include "resources.hpp"
#include "reconstruct_type.hpp"
#include "reference.hpp"
#include "static_string.hpp"

template <typename T, T &rsrc>
struct resource_injector {
	static auto main(reference <rsrc> &, const InjectionState &state) {
		static_assert(false, ($ss("reference injector for ") + $ss_type(T) + $ss(" has not been implemented yet")).view());
		return state.next(false, false);
	}
};

template <typename T, StructuredBuffer <T> &rsrc>
struct resource_injector <StructuredBuffer <T>, rsrc> {
	static auto main(reference <rsrc> &value, const InjectionState &state) {
		auto grsrc = resource_intrinsic <structured_buffer_reflection <T>> ::intrinsic(0);
		$tsb.context.add_global_resource <rsrc> (grsrc);
		injector <T> ::main(value, grsrc);
		return state.next(false, false);
	}
};

template <typename T, size_t D, Sampler <T, D> &rsrc>
struct resource_injector <Sampler <T, D>, rsrc> {
	static auto main(reference <rsrc> &value, const InjectionState &state) {
		auto grsrc =  resource_intrinsic <sampler_reflection <T, D>> ::intrinsic(0);
		$tsb.context.add_global_resource <rsrc> (grsrc);
		value.ref = grsrc;
		return state.next(false, false);
	}
};

template <typename T, ParameterBlock <T> &rsrc>
struct resource_injector <ParameterBlock <T>, rsrc> {
	static auto main(reference <rsrc> &value, const InjectionState &state) {
		using R = expand_reflection_t <T>;
		using F = parameter_block_filter_t <
			aggregate_reflection <AutoGenerated>,
			sequence <>,
			field_trace <R>
		>;

		using Uniform = typename F::uniform;
		using Resources = typename F::resources;

		// Process the potential constant block
		uint32_t counter = 0;

		if constexpr (!std::same_as <Uniform, void>) {
			auto type = reconstruct_type <Uniform> ();
			auto grsrc = jems::global_resource(type, GlobalResource::eXConstant, std::nullopt, counter++);
			$tsb.context.add_global_resource <rsrc> (grsrc);
			injector <Uniform> ::main(value, grsrc);
		}

		// Process any resources
		auto proc = [&](auto x) {
			using trace = std::decay_t <decltype(x)>;
			using resource = typename trace::value_type;
			auto grsrc = resource_intrinsic <resource> ::intrinsic(counter++);
			$tsb.context.add_global_resource <rsrc> (grsrc);
			injector <trace> ::main(value, grsrc);
			return true;
		};

		std::apply([&](auto ... xs) {
			std::make_tuple(proc(xs)...);
		}, typename Resources::tuple());

		return state.next(false, false);
	}
};
