#pragma once

#include "../dsl/instructions.hpp"
#include "../dsl/jems.hpp"
#include "context.hpp"
#include "reconstruct_type.hpp"
#include "stage.hpp"
#include "static_string.hpp"
#include "resources.hpp"
#include "parameter_block_filter.hpp"

template <Stage S>
void inject_execution_model()
{
	if constexpr (S == Stage::RepresentationalVertex)
		$tsb.context.model = ExecutionModel::eVulkanVertex;
	else
		static_assert(false, "no execution model for stage");
}

template <typename T>
void inject_item(T &item, Reference ref)
{
	if constexpr (std::is_base_of_v <jems::handle, T>)
		item.ref = ref;
	else
		static_assert(false, ($ss("failed to inject reference into item of type ") + $ss_type(T)).view());
}

struct InjectionState {
	size_t argidx;
	size_t threadidx;

	struct Delta {
		bool argument;
		bool thread_input;
	};

	InjectionState next(Delta delta) const {
		return {
			.argidx = argidx + delta.argument,
			.threadidx = threadidx + delta.thread_input,
		};
	}
};

template <Stage S, typename T>
struct stage_argument_injector {};

// For subroutines, normals arguments are normal arguments
template <typename T>
struct stage_argument_injector <Stage::Undefined, T> {
	static auto apply(T &value, const InjectionState &state) {
		auto type = reconstruct_type <T> ();
		auto arg = Argument(type, state.argidx);
		$tsb.context.add_argument(arg);
		inject_item(value, jems::intrinsic(arg));
		return InjectionState::Delta {
			.argument = true,
			.thread_input = false,
		};
	}
};

// Speciliazed reference handler; agnostic to the stage
template <typename T, T &rsrc>
struct resource_injector {
	static auto apply(reference <rsrc> &value, const InjectionState &state) {
		static_assert(false, ($ss("reference injector for ") + $ss_type(T) + $ss(" has not been implemented yet")).view());
		return InjectionState::Delta {
			.argument = false,
			.thread_input = false,
		};
	}
};

template <typename T, size_t D, Sampler <T, D> &rsrc>
struct resource_injector <Sampler <T, D>, rsrc> {
	static auto apply(reference <rsrc> &value, const InjectionState &state) {
		auto type = jems::type(VectorType <T, D> ());
		auto grsrc = jems::intrinsic(GlobalResource(type, GlobalResource::eSampler));
		value.ref = grsrc;

		return InjectionState::Delta {
			.argument = false,
			.thread_input = false,
		};
	}
};

template <typename T, ParameterBlock <T> &rsrc>
struct resource_injector <ParameterBlock <T>, rsrc> {
	static auto apply(reference <rsrc> &value, const InjectionState &state) {
		using R = expand_reflection_t <T>;
		using F = parameter_block_filter_t <
			aggregate_reflection <AutoGenerated>,
			sequence <>, R
		>;

		using Uniform = typename F::uniform;
		using Resources = typename F::resources;

		fmt::println("resource injector for filtered result: {}", $ss_type(F).view());
		fmt::println("\tuniform: {}", $ss_type_indented(Uniform, 1).view());
		fmt::println("\tresources: {}", $ss_type_indented(Resources, 1).view());

		return InjectionState::Delta {
			.argument = false,
			.thread_input = false,
		};
	}
};

// For all stages, handling resource references is basically the same
template <Stage S, auto &rsrc>
struct stage_argument_injector <S, reference <rsrc>> {
	using T = std::decay_t <decltype(rsrc)>;

	static auto apply(reference <rsrc> &value, const InjectionState &state) {
		return resource_injector <T, rsrc> ::apply(value, state);
	}
};

// For vertex and fragment shaders, normal arguments are thread inputs
template <Stage S, typename T>
requires (S == Stage::RepresentationalVertex || S == Stage::RepresentationalFragment)
struct stage_argument_injector <S, T> {
	static auto apply(T &value, const InjectionState &state) {
		auto type = reconstruct_type <T> ();
		auto tin = ThreadInput(type, state.threadidx);
		$tsb.context.add_thread_input(tin);
		inject_item(value, jems::intrinsic(tin));
		return InjectionState::Delta {
			.argument = false,
			.thread_input = true,
		};
	}
};

// Always ignore the implicit context
template <Stage S, auto & ... refs>
struct stage_argument_injector <S, implicit_context <refs...>> {
	static auto apply(auto &value, const InjectionState &state) {
		return InjectionState::Delta { false, false };
	}
};

template <Stage S, size_t Index, typename ... Args>
void inject_arguments(std::tuple <Args...> &args, const InjectionState &state)
{
	auto &value = std::get <Index> (args);
	using T = std::decay_t <decltype(value)>;

	auto delta = stage_argument_injector <S, T> ::apply(value, state);
	if constexpr (Index + 1 < sizeof...(Args))
		inject_arguments <S, Index + 1> (args, state.next(delta));
}
