#pragma once

#include "../dsl/instructions.hpp"
#include "../dsl/jems.hpp"
#include "context.hpp"
#include "reconstruct_type.hpp"
#include "stage.hpp"
#include "static_string.hpp"
#include "resources.hpp"
#include "parameter_block_filter.hpp"

template <Stage S>
void inject_execution_model()
{
	if constexpr (S == Stage::RepresentationalVertex)
		$tsb.context.model = ExecutionModel::eVulkanVertex;
	else
		static_assert(false, "no execution model for stage");
}

// Injecting with a given reference
template <typename T>
struct injector {
	static void main(T &item, Reference ref) {
		static_assert(false, ($ss("failed to inject reference into item of type ") + $ss_type(T)).view());
	}
};

template <typename T>
requires std::is_base_of_v <jems::handle, T>
struct injector <T> {
	static void main(T &item, Reference ref) {
		item.ref = ref;
	}
};

// Injecting a reference into a resource at a specific access chain
template <typename T, size_t ... Is>
struct injector <field_trace <T, Is...>> {
	template <auto &rsrc>
	static void main(reference <rsrc> &value, Reference ref) {
		static_access_chain <Is...> (value).ref = ref;
	}
};

template <typename ... Ts>
struct injector <aggregate_reflection <AutoGenerated, Ts...>> {
	template <auto &rsrc>
	static void main(reference <rsrc> &value, Reference ref) {
		uint32_t counter = 0;
		auto inject = [&](auto x) {
			auto access = jems::field_access(ref, counter++);
			injector <decltype(x)> ::main(value, access);
			return true;
		};

		std::apply([&](auto ... xs) {
			std::make_tuple(inject(xs)...);
		}, std::tuple <Ts...> ());
	}
};

// Progresive injection while tracking order
struct InjectionState {
	size_t argidx;
	size_t threadidx;

	struct Delta {
		bool argument;
		bool thread_input;
	};

	InjectionState next(Delta delta) const {
		return {
			.argidx = argidx + delta.argument,
			.threadidx = threadidx + delta.thread_input,
		};
	}
};

template <Stage S, typename T>
struct stage_argument_injector {};

// For subroutines, normals arguments are normal arguments
template <typename T>
struct stage_argument_injector <Stage::Undefined, T> {
	static auto main(T &value, const InjectionState &state) {
		auto type = reconstruct_type <T> ();
		auto arg = Argument(type, state.argidx);
		$tsb.context.add_argument(arg);
		injector <T> ::main(value, jems::argument(arg));
		return InjectionState::Delta {
			.argument = true,
			.thread_input = false,
		};
	}
};

// Generating intinsics for resources
template <typename T>
struct resource_intrinsic {
	static auto intrinsic(uint32_t binding) {
		static_assert(false, ($ss("resource intrinsic generator not implemented for ") + $ss_type(T)).view());
	}
};

template <typename T>
struct resource_intrinsic <structured_buffer_reflection <T>> {
	static auto intrinsic(uint32_t binding) {
		auto type = reconstruct_type <T> ();
		auto grsrc = jems::global_resource(type, GlobalResource::eStorageBuffer, std::nullopt, binding);
		return grsrc;
	}
};

template <typename T, size_t D>
struct resource_intrinsic <sampler_reflection <T, D>> {
	static auto intrinsic(uint32_t binding) {
		auto type = jems::type(VectorType <T, D> ());
		auto grsrc = jems::global_resource(type, GlobalResource::eSampler, std::nullopt, binding);
		return grsrc;
	}
};

// Speciliazed reference handler; agnostic to the stage
template <typename T, T &rsrc>
struct resource_injector {
	static auto main(reference <rsrc> &value, const InjectionState &state) {
		static_assert(false, ($ss("reference injector for ") + $ss_type(T) + $ss(" has not been implemented yet")).view());
		return InjectionState::Delta {
			.argument = false,
			.thread_input = false,
		};
	}
};

template <typename T, size_t D, Sampler <T, D> &rsrc>
struct resource_injector <Sampler <T, D>, rsrc> {
	static auto main(reference <rsrc> &value, const InjectionState &state) {
		value.ref = resource_intrinsic <sampler_reflection <T, D>> ::intrinsic();
		return InjectionState::Delta {
			.argument = false,
			.thread_input = false,
		};
	}
};

template <typename T, ParameterBlock <T> &rsrc>
struct resource_injector <ParameterBlock <T>, rsrc> {
	static auto main(reference <rsrc> &value, const InjectionState &state) {
		using R = expand_reflection_t <T>;
		using F = parameter_block_filter_t <
			aggregate_reflection <AutoGenerated>,
			sequence <>,
			field_trace <R>
		>;

		using Uniform = typename F::uniform;
		using Resources = typename F::resources;

		// Process the potential constant block
		uint32_t counter = 0;

		if constexpr (!std::same_as <Uniform, void>) {
			auto type = reconstruct_type <Uniform> ();
			auto grsrc = jems::global_resource(type, GlobalResource::eXConstant, std::nullopt, counter++);
			injector <Uniform> ::main(value, grsrc);
		}

		// Process any resources
		auto proc = [&](auto x) {
			using trace = std::decay_t <decltype(x)>;
			using resource = typename trace::value_type;
			auto grsrc = resource_intrinsic <resource> ::intrinsic(counter++);
			injector <trace> ::main(value, grsrc);
			return true;
		};

		std::apply([&](auto ... xs) {
			std::make_tuple(proc(xs)...);
		}, typename Resources::tuple());

		return InjectionState::Delta {
			.argument = false,
			.thread_input = false,
		};
	}
};

// For all stages, handling resource references is basically the same
template <Stage S, auto &rsrc>
struct stage_argument_injector <S, reference <rsrc>> {
	using T = std::decay_t <decltype(rsrc)>;

	static auto main(reference <rsrc> &value, const InjectionState &state) {
		return resource_injector <T, rsrc> ::main(value, state);
	}
};

// For vertex and fragment shaders, normal arguments are thread inputs
template <Stage S, typename T>
requires (S == Stage::RepresentationalVertex || S == Stage::RepresentationalFragment)
struct stage_argument_injector <S, T> {
	static auto main(T &value, const InjectionState &state) {
		auto type = reconstruct_type <T> ();
		auto tin = ThreadInput(type, state.threadidx);
		$tsb.context.add_thread_input(tin);
		inject_item(value, jems::thread_input(tin));
		return InjectionState::Delta {
			.argument = false,
			.thread_input = true,
		};
	}
};

// Always ignore the implicit context
template <Stage S, auto & ... refs>
struct stage_argument_injector <S, implicit_context <refs...>> {
	static auto main(auto &value, const InjectionState &state) {
		return InjectionState::Delta { false, false };
	}
};

template <Stage S, size_t Index, typename ... Args>
void inject_arguments(std::tuple <Args...> &args, const InjectionState &state)
{
	auto &value = std::get <Index> (args);
	using T = std::decay_t <decltype(value)>;

	auto delta = stage_argument_injector <S, T> ::main(value, state);
	if constexpr (Index + 1 < sizeof...(Args))
		inject_arguments <S, Index + 1> (args, state.next(delta));
}
