#pragma once

#include "reflection.hpp"
#include "resources.hpp"

// TODO: need to override field_name for autogenerated...
struct AutoGenerated {};

template <typename A, typename B>
struct uniform_merge {
	using type = aggregate_reflection <AutoGenerated>;
};

template <typename ... Ts, typename B>
struct uniform_merge <aggregate_reflection <AutoGenerated, Ts...>, B> {
	using type = aggregate_reflection <AutoGenerated, Ts..., B>;
};

// <Uniform> holds all the uniform/push constant parts
// and <Resources...> are all the GRVs accumulated
template <typename Uniform, typename Resources, typename ... Ts>
struct parameter_block_filter {
	using uniform = Uniform;
	using resources = Resources;

	using type = parameter_block_filter <Uniform, Resources>;
	// NOTE: next is only for debugging the metaprogramming
	using next = type;
};

template <typename Uniform, typename Resources, typename ... Ts>
using parameter_block_filter_t = parameter_block_filter <Uniform, Resources, Ts...> ::type;

template <typename Uniform, typename Resources, typename T, typename ... Ts>
requires is_resource_reflection_v <T>
struct parameter_block_filter <Uniform, Resources, T, Ts...> {
	using resources = typename Resources::template append_t <T>;
	using type = parameter_block_filter_t <Uniform, resources, Ts...>;
	using next = parameter_block_filter <Uniform, resources, Ts...>;
};

template <typename Uniform, typename Resources, typename T, typename ... Ts>
struct parameter_block_filter <Uniform, Resources, T, Ts...> {
	using merged = uniform_merge <Uniform, T> ::type;
	using type = parameter_block_filter_t <merged, Resources, Ts...>;
	using next = parameter_block_filter <merged, Resources, Ts...>;
};

template <typename Uniform, typename Resources, typename T, typename ... Ts>
struct parameter_block_filter <Uniform, Resources, parameter_block_reflection <T>, Ts...> {
	using type = parameter_block_filter_t <Uniform, Resources, T, Ts...>;
	using next = parameter_block_filter <Uniform, Resources, T, Ts...>;
};

template <typename Uniform, typename Resources, typename T, typename ... TFields, typename ... Ts>
struct parameter_block_filter <Uniform, Resources, aggregate_reflection <T, TFields...>, Ts...> {
	using type = parameter_block_filter_t <Uniform, Resources, TFields..., Ts...>;
	using next = parameter_block_filter <Uniform, Resources, TFields..., Ts...>;
};
