#pragma once

#include <cstdlib>

#include "../util/meta.hpp"
#include "static_string.hpp"
#include "field_name_injection.hpp"
#include "macro_hell.hpp"
#include "this_injection.hpp"

// Reflection types
template <typename T>
struct primitive_reflection {};

template <typename Original, typename ... Ts>
struct aggregate_reflection {
	static constexpr size_t field_count = sizeof...(Ts);
};

template <typename T, int64_t N>
struct array_reflection {};

template <typename T>
struct parameter_block_reflection {};

template <typename T>
struct structured_buffer_reflection {};

template <typename T, size_t D>
struct sampler_reflection {};

template <auto &ref, typename T>
struct reference_reflection {};

template <typename R, typename ... Args>
struct function_reflection {};

// Specific kinds of reflection
template <typename T>
struct is_primitive_reflection : std::false_type {};

template <typename U>
struct is_primitive_reflection <primitive_reflection <U>> : std::true_type {};

template <typename T>
constexpr bool is_primitive_reflection_v = is_primitive_reflection <T> ::value;

template <typename T>
struct is_aggregate_reflection : std::false_type {};

template <typename Original, typename ... Ts>
struct is_aggregate_reflection <aggregate_reflection <Original, Ts...>> : std::true_type {};

template <typename T>
constexpr bool is_aggregate_reflection_v = is_aggregate_reflection <T> ::value;

// Querying reflection status
template <typename T>
constexpr bool has_reflection()
{
	if constexpr (requires { T::_ugp_has_reflection; })
		return T::_ugp_has_reflection;
	else
		return false;
}

template <typename T>
constexpr bool has_aggregate_reflection()
{
	if constexpr (has_reflection <T> ())
		return is_aggregate_reflection_v <typename T::reflection>;
	else
		return false;
}

template <typename T>
constexpr bool has_primitive_reflection()
{
	if constexpr (has_reflection <T> ())
		return is_primitive_reflection_v <typename T::reflection>;
	else
		return false;
}

template <typename T>
concept reflected = has_reflection <T> ();

template <typename T>
concept aggregate = has_aggregate_reflection <T> ();

template <typename T>
concept primitive = has_primitive_reflection <T> ();

// Type registry for wholistic reflection
template <typename T, std::size_t Index>
struct scaffold_field {
	using value_type = T;
	static constexpr auto index = Index;
};

#define AGGREGATE_FIELD_GENERATOR(T, field) std::declval <decltype(field)> (),
// TODO: some way to skip?
#define AGGREGATE_SCAFFOLD_GENERATOR(T, field)	\
	scaffold_field <decltype(T::field), (__COUNTER__ - counter_base - 1)> field;
#define AGGREGATE_FIELD_REFERENCE_GENERATOR(T, field)	\
	else if constexpr (D == ((__COUNTER__ - 1) - counter_base)) { return field; }

#define UGP_REFLECTION_STAMP static constexpr bool _ugp_has_reflection = true

template <typename Original, typename ... Ts>
auto new_aggregate_reflection(sequence <Ts...>)
	-> aggregate_reflection <Original, Ts...>;

#define $reflection(...)							\
	THIS_INJECTION();							\
	using reflection = decltype(new_aggregate_reflection <This> (		\
		sequence {							\
			MAP(AGGREGATE_FIELD_GENERATOR, /* NA */ , __VA_ARGS__)	\
		}								\
	));									\
	struct scaffold {							\
		static constexpr size_t counter_base = __COUNTER__;		\
		MAP(AGGREGATE_SCAFFOLD_GENERATOR, This, __VA_ARGS__)		\
	};									\
	MAP(FIELD_NAME_INJECTION, This, __VA_ARGS__)				\
	UGP_REFLECTION_STAMP;							\
	static inline AutoGenerated _ugp_reference_default;			\
	template <size_t D>							\
	auto &_ugp_field_reference() {						\
		static constexpr size_t counter_base = __COUNTER__;		\
		if constexpr (false) {}						\
		MAP(AGGREGATE_FIELD_REFERENCE_GENERATOR, /* NA */, __VA_ARGS__)	\
		else {								\
			static_assert(false,					\
		 		($ss("out of bounds field reference access of ")\
		 		+ $ss_type(This)).view());			\
			return _ugp_reference_default;				\
		}								\
	}									\
	template <size_t D>							\
	auto &_ugp_field_reference() const {					\
		static constexpr size_t counter_base = __COUNTER__;		\
		if constexpr (false) {}						\
		MAP(AGGREGATE_FIELD_REFERENCE_GENERATOR, /* NA */, __VA_ARGS__)	\
		else {								\
			static_assert(false,					\
		 		($ss("out of bounds field reference access of ")\
		 		+ $ss_type(This)).view());			\
			return _ugp_reference_default;				\
		}								\
	}
	// TODO: macrofy the above

// Access chain through static indices
template <typename T, size_t I, size_t ... Is>
struct static_access_chain_handler {
	static auto &main(T &value) {
		static_assert(false, ($ss("static access chain not implemented for ") + $ss_type(T)).view());
		return value;
	}
};

// Aggregate already have a method for this, just recurse over that
template <typename T, size_t I, size_t ... Is>
requires (has_aggregate_reflection <T> ())
struct static_access_chain_handler <T, I, Is...> {
	static auto &main(T &value) {
		auto &one = value.template _ugp_field_reference <I> ();

		using U = std::remove_reference_t <decltype(one)>;
		if constexpr (sizeof...(Is))
			return static_access_chain_handler <U, Is...> ::main(one);
		else
			return one;
	}
};

template <size_t I, size_t ... Is, typename T>
requires (has_reflection <T> ())
auto &static_access_chain(T &value)
{
	// // TODO: do we really need to use reflection??
	// using R = typename T::reflection;
	// using Rexp = expand_reflection_t <R>;
	return static_access_chain_handler <T, I, Is...> ::main(value);
}
