#include <fmt/printf.h>

#include <ugp.hpp>

struct VertexAttributes {
	vec3 position;
	vec3 normal;
	vec2 uv;

	// TODO: intrinscs must be listed as members... (or parameters...)

	$reflection(position, normal, uv);
};

struct RasterForward {
	Position svpos;
	Smooth <vec3> position;
	Smooth <vec3> normal;
	Smooth <vec2> uv;

	$reflection(svpos, position, normal, uv);
};

// RasterForward == FragmentAttributes after discarding Position
// and intrinscs on both sides and including order
struct FragmentAttributes {
	vec3 position;
	vec3 normal;
	vec2 uv;

	// NOTE: Interpolation qualifiers are inferred (should not necessary be re-declared here...)

	$reflection(position, normal, uv);
};

struct MVP {
	mat4 model;
	mat4 view;
	mat4 proj;

	$reflection(model, view, proj);
};

struct VertexGroup {
	MVP mvp;
	vec3 another;

	$reflection(mvp, another);
};

using VVR = VertexGroup::reflection;
using VVRex = expand_reflection_t <VertexGroup>;

ParameterBlock <MVP> mvp;

struct Material {
	i32 scale;
	Sampler2D diffuse;
	Sampler2D specular;
	StructuredBuffer <i32> layers;

	struct Subsurface {
		vec3 point;
		vec3 normal;
		Sampler3D volume;

		$reflection(point, normal, volume);
	} subsurface;
	
	$reflection(scale, diffuse, specular, layers, subsurface);
};

ParameterBlock <Material> material;

using R = expand_reflection_t <decltype(material)>;

using filtered = parameter_block_filter_t <
	aggregate_reflection <AutoGenerated>,
	sequence <>, field_trace <R>
>;
using filtered_debug = parameter_block_filter <
	aggregate_reflection <AutoGenerated>,
	sequence <>, field_trace <R>
> ::next::next::next::next::next::next;

// template <int>
// struct A {};
//
// struct X {
// 	int32_t value;
// 	[[no_unique_address]] A <0> a1;
// 	[[no_unique_address]] A <1> a2;
// 	[[no_unique_address]] A <2> a3;
// };
//
// static_assert(sizeof(X) == 4);

// namespace combinators {
//
// template <Topology T>
// struct traditional_graphics_pipeline {
// 	vk::CullModeFlags culling;
// };
//
// template <Topology T>
// using tgp = traditional_graphics_pipeline <T>;
//
// } // namespace combinators

// // NOTE: Templates are allowed as follows:
// template <int N>
// auto ftn = $fn(std::array <i32, N> x, i32 y[N]) -> $returns(void) {
// };

int main()
{
	reference <material> mat;

	auto &r0 = static_access_chain <0> (mat);
	auto &r4 = static_access_chain <4> (mat);
	auto &r40 = static_access_chain <0> (r4);

	// static_access_chain <1> (static_access_chain <3> (mat)) = vec3();
	// static_access_chain <3, 1> (mat) = vec3();

	// // TODO: start rolling out some basic tests...
	// auto session_info = Session::Info {
	// 	.validation_bootstrap = false,
	// };
	//
	// auto [session, dld] = Session::from(session_info);
	//
	// auto device_info = Device::Info();
	// auto device = Device::from(session, dld, device_info);

	// NOTE: we actually cant compile the shaders until the we understand the whole pipeline...
	// defer device supplication to the pipeline point?
	// no, it still makes sense to pair shaders with device;
	// then multi-gpu programming is easier
	//
	// TODO: technically thread inputs should be in the context... make context in terms of types...

	// auto vs = $vertex $fn(vec2 pos, mat4 mat, $use(mvp)) -> $returns(
	// 	Position,
	// 	Smooth <vec3>,
	// 	Flat <i32>
	// ) {
	// 	$return std::tuple {
	// 		Position(mat * vec4(pos, 0, 1)),
	// 		vec3(pos, 1.4),
	// 		12,
	// 	};
	// };
	
	auto vs = $vertex $fn($use(material)) -> $returns(void) {
		// TODO: confirm that material's fields are all populated...
		vec2 uv = vec2(0, 1);

		f32 s = dot(material.subsurface.point, material.subsurface.normal);

		vec3 result = material.diffuse.sample(uv);
	};

	fmt::println("assembly:");
	fmt::println("{}", generators::Assembly(vs).generate());

	static_assert(not has_aggregate_reflection <i32> ());
	static_assert(not has_aggregate_reflection <mat4> ());
	static_assert(has_aggregate_reflection <MVP> ());
	static_assert(has_aggregate_reflection <Material> ());

	// fmt::println("glsl:");
	// fmt::println("{}", generators::GLSL(vs).generate());
	
	// static_assert(!has_reflection <int> ());
	//
	// using x = reflection_expander <i32> ::type;
	// using y = reflection_expander <MVP> ::type;
	//
	// Block block;
	// if (auto s = jems::scope(block)) {
	// 	auto type = reconstruct_type <MVP> ();
	// 	auto rsrc = jems::intrinsic(GlobalResource(type, GlobalResource::ePushConstant));
	// 	auto field = jems::field_access(rsrc, 1);
	// }
	//
	// fmt::println("assembly:");
	// fmt::println("{}", generators::Assembly(block).generate());
}
