#!/usr/bin/env python3
"""
Generate explicit instantiations for templates based on @instantiate annotations.

Annotation format:
    // @instantiate: template_name <A, B> where A=[type1, type2], B=[type3]

This generates a cartesian product of all combinations.
"""

import argparse
import re
from itertools import product
from pathlib import Path


def split_where_clauses(where_clause):
    """Split by comma, but respect brackets."""
    parts = []
    current = ""
    depth = 0
    for char in where_clause:
        if char == "[":
            depth += 1
        elif char == "]":
            depth -= 1
        elif char == "," and depth == 0:
            parts.append(current.strip())
            current = ""
            continue
        current += char
    if current.strip():
        parts.append(current.strip())
    return parts


def parse_values(values_str):
    """Parse comma-separated values, respecting brackets."""
    values = []
    current = ""
    depth = 0
    for char in values_str:
        if char == "<":
            depth += 1
        elif char == ">":
            depth -= 1
        elif char == "," and depth == 0:
            values.append(current.strip())
            current = ""
            continue
        current += char
    if current.strip():
        values.append(current.strip())
    return values


def generate_instantiations(headers, output_path):
    """Scan headers for @instantiate annotations and generate instantiations."""

    instantiations = []

    for header_path in headers:
        header = Path(header_path)
        if not header.exists():
            print(f"Warning: Header not found: {header}")
            continue

        content = header.read_text()
        lines = content.split("\n")

        for line in lines:
            if "@instantiate:" not in line:
                continue

            # Parse: @instantiate: template_name <params> where clauses
            pattern = re.compile(
                r"@instantiate:\s*(\w+)\s*<([^>]+)>\s*where\s+(.+)", re.IGNORECASE
            )
            match = pattern.search(line)
            if not match:
                continue

            template_name = match.group(1)
            params_str = match.group(2)
            where_clause = match.group(3)

            # Parse template parameter names in order
            param_names = [p.strip() for p in params_str.split(",")]

            # Parse where clauses: A=[int32_t, float], B=[2, 3]
            param_values = {}
            for clause in split_where_clauses(where_clause):
                param_match = re.match(r"(\w+)=\[(.+)\]", clause)
                if not param_match:
                    continue

                param_name = param_match.group(1)
                values_str = param_match.group(2)
                param_values[param_name] = parse_values(values_str)

            # Build value lists in the same order as param_names
            value_lists = []
            for param in param_names:
                if param in param_values:
                    value_lists.append(param_values[param])
                else:
                    value_lists.append(
                        [param]
                    )  # Use param itself if not in where clause

            # Generate cartesian product
            for values in product(*value_lists):
                instantiation = (
                    f"template class rcgp::{template_name}<{', '.join(values)}>;"
                )
                instantiations.append(instantiation)

    # Generate output
    output = []
    output.append("// Auto-generated - DO NOT EDIT")
    output.append("// Generated by: generate_instantiations.py")
    output.append("")
    output.append("#include <rcgp.hpp>")
    output.append("")
    output.append("namespace rcgp {")
    output.append("")

    for inst in instantiations:
        output.append(inst)

    output.append("")
    output.append("} // namespace rcgp")

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(output))

    print(f"Generated {len(instantiations)} instantiations to {output_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate explicit template instantiations"
    )
    parser.add_argument("--output", "-o", required=True, help="Output file path")
    parser.add_argument(
        "headers", nargs="+", help="Header files to scan for @instantiate annotations"
    )

    args = parser.parse_args()
    generate_instantiations(args.headers, args.output)


if __name__ == "__main__":
    main()
