from __future__ import annotations

from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[2]
INCLUDE_DIR = ROOT / "include" / "dsl"
SOURCE_DIR = ROOT / "source" / "dsl"

HEADER_PREAMBLE = "// Generated by generate_instruction_enums.py. Do not edit by hand."


def strip_comments(text: str) -> str:
    lines = []
    for line in text.splitlines():
        if "//" in line:
            line = line.split("//", 1)[0]
        lines.append(line)
    return "\n".join(lines)


def parse_enums(text: str) -> list[tuple[str, list[str]]]:
    text = strip_comments(text)
    pattern = re.compile(r"enum\s+class\s+(\w+)\s*\{(.*?)\};", re.S)
    enums: list[tuple[str, list[str]]] = []
    for match in pattern.finditer(text):
        name = match.group(1)
        body = match.group(2)
        entries = []
        for item in body.split(","):
            item = item.strip()
            if not item:
                continue
            item = item.split("=", 1)[0].strip()
            entries.append(item)
        enums.append((name, entries))
    return enums


def strip_enum_prefix(name: str) -> str:
    if name.startswith("e") and len(name) > 1:
        return name[1:]
    return name


def generate_cpp(enums: list[tuple[str, list[str]]]) -> list[str]:
    lines: list[str] = []
    lines.append(HEADER_PREAMBLE)
    lines.append('#include "dsl/instruction_enums.hpp"')
    lines.append("")
    lines.extend(
        [
            "#include <array>",
            "#include <cstddef>",
            "#include <string_view>",
            "#include <utility>",
            "",
            "namespace rcgp {",
            "",
        ]
    )

    for enum_name, entries in enums:
        array_name = f"k{enum_name}Names"
        lines.append(
            f"static constexpr std::array<std::string_view, {len(entries)}> {array_name} = {{"
        )
        for entry in entries:
            repr_value = strip_enum_prefix(entry)
            if enum_name == "SwizzleCode":
                repr_value = repr_value.lower()
            lines.append(f'\t"{repr_value}",')
        lines.append("};")
        lines.append("")
        lines.append(f"std::string_view repr({enum_name} value)")
        lines.append("{")
        lines.append("\tauto raw = std::to_underlying(value);")
        lines.append(
            "\tif (raw < 0 || static_cast<size_t>(raw) >= " + array_name + ".size())"
        )
        lines.append('\t\treturn "Unknown";')
        lines.append("\treturn " + array_name + "[static_cast<size_t>(raw)];")
        lines.append("}")
        lines.append("")

    lines.append("} // namespace rcgp")
    return lines


def write(path: Path, lines: list[str]) -> None:
    path.write_text("\n".join(lines) + "\n")


def main() -> None:
    header = INCLUDE_DIR / "instruction_enums.hpp"
    enums = parse_enums(header.read_text())
    cpp_lines = generate_cpp(enums)
    write(SOURCE_DIR / "pygen_instruction_enums.cpp", cpp_lines)


if __name__ == "__main__":
    main()
