from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
INCLUDE_DIR = ROOT / 'include' / 'dsl'
SOURCE_DIR = ROOT / 'source' / 'dsl'

HEADER_PREAMBLE = """// Generated by generate_instantiations.py. Do not edit by hand.
"""


def write(path: Path, lines: list[str]) -> None:
    path.write_text('\n'.join(lines) + '\n')


def gen_jems_instantiations() -> tuple[list[str], list[str]]:
    scalar_types = ['int32_t', 'uint32_t', 'float']
    scalar_types_with_bool = ['bool'] + scalar_types
    vector_dims = [2, 3, 4]
    matrix_dims_type = [2, 3, 4]
    matrix_dims_all = [2, 3, 4]
    matrix_dims_ops = [2, 3, 4]

    header = []
    header.append('#pragma once')
    header.append(HEADER_PREAMBLE.strip())
    header.append('')
    header.extend([
        '#include "jems.hpp"',
        '#include "scalar.hpp"',
        '#include "vector_base.hpp"',
        '#include "vector.hpp"',
        '#include "matrix.hpp"',
        '',
        'namespace rcgp {',
        '',
    ])

    externs: list[str] = []

    def add_extern(name: str, args: str) -> None:
        externs.append(f'extern template struct jems::{name} <{args}>;')

    # constant / constant_loc
    for t in scalar_types_with_bool + ['std::string']:
        add_extern('constant', t)
        add_extern('constant_loc', t)

    add_extern('type', 'Primitive')
    add_extern('type_loc', 'Primitive')

    add_extern('type', 'Array')
    add_extern('type_loc', 'Array')
    add_extern('type', 'Struct')
    add_extern('type_loc', 'Struct')

    # argument/thread_input/thread_output and loc
    for name, arg in [
        ('argument', 'Argument'),
        ('stage_input', 'StageInput'),
        ('stage_output', 'StageOutput'),
    ]:
        add_extern(name, arg)
        add_extern(name + '_loc', arg)

    # system_value and loc
    add_extern('system_value', 'SystemValue')
    add_extern('system_value_loc', 'SystemValue')

    # global_resource and loc (common shape)
    add_extern('global_resource', 'jems::handle, GlobalResourceKind, GlobalResourceLayout, GlobalResourceAccess, std::nullopt_t, uint32_t')
    add_extern('global_resource_loc', 'jems::handle, GlobalResourceKind, GlobalResourceLayout, GlobalResourceAccess, std::nullopt_t, uint32_t')

    # field_access and loc
    for idx_t in ['uint32_t', 'size_t']:
        add_extern('field_access', f'Reference, {idx_t}')
        add_extern('field_access_loc', f'Reference, {idx_t}')

    # array_access and loc (int/uint indices)
    for idx_t in ['int32_t', 'uint32_t']:
        add_extern('array_access', f'Reference, scalar <{idx_t}>')
        add_extern('array_access_loc', f'Reference, scalar <{idx_t}>')

    # swizzle and loc for vector types
    for t in scalar_types:
        for d in vector_dims:
            add_extern('swizzle', f'SwizzleCode, vector <{t}, {d}>')
            add_extern('swizzle_loc', f'SwizzleCode, vector <{t}, {d}>')

    # operation and loc for common shapes
    for t in scalar_types:
        add_extern('operation', f'OperationCode, scalar <{t}>, scalar <{t}>')
        add_extern('operation_loc', f'OperationCode, scalar <{t}>, scalar <{t}>')

    for t in scalar_types:
        for d in vector_dims:
            add_extern('operation', f'OperationCode, vector <{t}, {d}>, vector <{t}, {d}>')
            add_extern('operation_loc', f'OperationCode, vector <{t}, {d}>, vector <{t}, {d}>')
            add_extern('operation', f'OperationCode, scalar <{t}>, vector <{t}, {d}>')
            add_extern('operation_loc', f'OperationCode, scalar <{t}>, vector <{t}, {d}>')
            add_extern('operation', f'OperationCode, vector <{t}, {d}>, scalar <{t}>')
            add_extern('operation_loc', f'OperationCode, vector <{t}, {d}>, scalar <{t}>')

    for t in scalar_types:
        for d in matrix_dims_ops:
            add_extern('operation', f'OperationCode, matrix <{t}, {d}, {d}>, vector <{t}, {d}>')
            add_extern('operation_loc', f'OperationCode, matrix <{t}, {d}, {d}>, vector <{t}, {d}>')
            add_extern('operation', f'OperationCode, matrix <{t}, {d}, {d}>, matrix <{t}, {d}, {d}>')
            add_extern('operation_loc', f'OperationCode, matrix <{t}, {d}, {d}>, matrix <{t}, {d}, {d}>')

    # builtin_intrinsic and loc (float only)
    add_extern('builtin_intrinsic', 'BuiltinIntrinsicCode, scalar <float>')
    add_extern('builtin_intrinsic_loc', 'BuiltinIntrinsicCode, scalar <float>')
    add_extern('builtin_intrinsic', 'BuiltinIntrinsicCode, scalar <float>, scalar <float>')
    add_extern('builtin_intrinsic_loc', 'BuiltinIntrinsicCode, scalar <float>, scalar <float>')
    for d in vector_dims:
        add_extern('builtin_intrinsic', f'BuiltinIntrinsicCode, vector <float, {d}>')
        add_extern('builtin_intrinsic_loc', f'BuiltinIntrinsicCode, vector <float, {d}>')
        add_extern('builtin_intrinsic', f'BuiltinIntrinsicCode, vector <float, {d}>, vector <float, {d}>')
        add_extern('builtin_intrinsic_loc', f'BuiltinIntrinsicCode, vector <float, {d}>, vector <float, {d}>')

    # construct_loc for vector constructors (common shapes)
    for t in scalar_types:
        add_extern('construct_loc', f'jems::type_loc <Primitive>, scalar <{t}>, scalar <{t}>')
        add_extern('construct_loc', f'jems::type_loc <Primitive>, scalar <{t}>')
        add_extern('construct_loc', f'jems::type_loc <Primitive>, vector_base <{t}, 4>')
        add_extern('construct_loc', f'jems::type_loc <Primitive>, vector_base <{t}, 2>, scalar <{t}>')
        add_extern('construct_loc', f'jems::type_loc <Primitive>, scalar <{t}>, scalar <{t}>, scalar <{t}>')
        add_extern('construct_loc', f'jems::type_loc <Primitive>, vector_base <{t}, 3>, scalar <{t}>')
        add_extern('construct_loc', f'jems::type_loc <Primitive>, vector_base <{t}, 2>, scalar <{t}>, scalar <{t}>')

    # construct for matrix (float square only)
    for d in matrix_dims_type:
        args = ', '.join(['scalar <float>'] * (d * d))
        add_extern('construct', f'jems::type <Primitive>, {args}')

    # store and loc for common shapes
    add_extern('store', 'jems::handle, scalar <float>')
    add_extern('store_loc', 'jems::handle, scalar <float>')
    add_extern('store', 'jems::handle, vector <float, 4>')
    add_extern('store_loc', 'jems::handle, vector <float, 4>')

    header.extend(externs)
    header.append('')
    header.append('} // namespace rcgp')

    cpp = []
    cpp.append('#include "dsl/pygen_jems_instantiations.hpp"')
    cpp.append('')
    cpp.append('namespace rcgp {')
    cpp.append('')
    cpp.extend([line.replace('extern template', 'template') for line in externs])
    cpp.append('')
    cpp.append('} // namespace rcgp')

    return header, cpp


def gen_intrinsics_arithmetic_instantiations() -> tuple[list[str], list[str], list[str]]:
    vector_dims = [2, 3, 4]

    intrinsics_header = []
    intrinsics_header.append('#pragma once')
    intrinsics_header.append(HEADER_PREAMBLE.strip())
    intrinsics_header.append('')
    intrinsics_header.append('#include "scalar.hpp"')
    intrinsics_header.append('#include "vector.hpp"')
    intrinsics_header.append('#include "matrix.hpp"')
    intrinsics_header.append('')
    intrinsics_header.append('namespace rcgp {')
    intrinsics_header.append('')

    intrinsics_externs: list[str] = []
    def add_intr(sig: str) -> None:
        intrinsics_externs.append(sig)

    for t in ['float', 'int32_t', 'uint32_t']:
        for d in vector_dims:
            add_intr(f'extern template scalar <{t}> dot(const vector <{t}, {d}> &a, const vector <{t}, {d}> &b);')

    for d in vector_dims:
        add_intr(f'extern template vector <float, {d}> normalize(const vector <float, {d}> &v);')

    add_intr('extern template vector <float, 3> cross(const vector <float, 3> &a, const vector <float, 3> &b);')

    for t in ['float', 'int32_t', 'uint32_t']:
        for n in [2, 3, 4]:
            for m in [2, 3, 4]:
                add_intr(f'extern template matrix <{t}, {m}, {n}> transpose(const matrix <{t}, {n}, {m}> &m);')

    for n in [2, 3, 4]:
        add_intr(f'extern template matrix <float, {n}, {n}> inverse(const matrix <float, {n}, {n}> &m);')

    for name in ['dFdx', 'dFdy', 'dFdxFine', 'dFdyFine']:
        add_intr(f'extern template scalar <float> {name}(const scalar <float> &v);')
        for d in vector_dims:
            add_intr(f'extern template vector <float, {d}> {name}(const vector <float, {d}> &v);')

    intrinsics_header.extend(intrinsics_externs)
    intrinsics_header.append('')
    intrinsics_header.append('} // namespace rcgp')

    arithmetic_header = []
    arithmetic_header.append('#pragma once')
    arithmetic_header.append(HEADER_PREAMBLE.strip())
    arithmetic_header.append('')
    arithmetic_header.append('#include "vector.hpp"')
    arithmetic_header.append('#include "matrix.hpp"')
    arithmetic_header.append('')
    arithmetic_header.append('namespace rcgp {')
    arithmetic_header.append('')

    arithmetic_externs: list[str] = []
    def add_arith(sig: str) -> None:
        arithmetic_externs.append(sig)

    for t in ['float', 'int32_t', 'uint32_t']:
        for n in [2, 3, 4]:
            for m in [2, 3, 4]:
                add_arith(
                    f'extern template vector <{t}, {m}> operator*(const matrix <{t}, {n}, {m}> &m, const vector <{t}, {n}> &v);'
                )

    for t in ['float', 'int32_t', 'uint32_t']:
        for n in [2, 3, 4]:
            for m in [2, 3, 4]:
                for k in [2, 3, 4]:
                    add_arith(
                        f'extern template matrix <{t}, {n}, {m}> operator*(const matrix <{t}, {n}, {k}> &a, const matrix <{t}, {k}, {m}> &b);'
                    )

    arithmetic_header.extend(arithmetic_externs)
    arithmetic_header.append('')
    arithmetic_header.append('} // namespace rcgp')

    cpp = []
    cpp.append('#include "dsl/intrinsics.hpp"')
    cpp.append('#include "dsl/arithmetic.hpp"')
    cpp.append('')
    cpp.append('namespace rcgp {')
    cpp.append('')
    cpp.extend([line.replace('extern template', 'template') for line in intrinsics_externs])
    cpp.extend([line.replace('extern template', 'template') for line in arithmetic_externs])
    cpp.append('')
    cpp.append('} // namespace rcgp')

    return intrinsics_header, arithmetic_header, cpp


def main() -> None:
    jems_header, jems_cpp = gen_jems_instantiations()
    intr_header, arith_header, intr_cpp = gen_intrinsics_arithmetic_instantiations()

    write(INCLUDE_DIR / 'pygen_jems_instantiations.hpp', jems_header)
    write(SOURCE_DIR / 'pygen_jems_instantiations.cpp', jems_cpp)
    write(INCLUDE_DIR / 'pygen_intrinsics_instantiations.hpp', intr_header)
    write(INCLUDE_DIR / 'pygen_arithmetic_instantiations.hpp', arith_header)
    write(SOURCE_DIR / 'pygen_intrinsics_arithmetic.cpp', intr_cpp)


if __name__ == '__main__':
    main()
