#pragma once

#define SWIZZLE_D2 \
	using self = vector_base <T, 2>; \
	using C1 = scalar <T>;\
	[[no_unique_address]] swizzle_component <Swizzle::eX, self, C1> x; \
	[[no_unique_address]] swizzle_component <Swizzle::eY, self, C1> y; \
	using C2 = vector <T, 2>;\
	[[no_unique_address]] swizzle_component <Swizzle::eXX, self, C2> xx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXY, self, C2> xy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYX, self, C2> yx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYY, self, C2> yy; \
	using C3 = vector <T, 3>;\
	[[no_unique_address]] swizzle_component <Swizzle::eXXX, self, C3> xxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXY, self, C3> xxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYX, self, C3> xyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYY, self, C3> xyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXX, self, C3> yxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXY, self, C3> yxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYX, self, C3> yyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYY, self, C3> yyy; \
	using C4 = vector <T, 4>;\
	[[no_unique_address]] swizzle_component <Swizzle::eXXXX, self, C4> xxxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXXY, self, C4> xxxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXYX, self, C4> xxyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXYY, self, C4> xxyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYXX, self, C4> xyxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYXY, self, C4> xyxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYYX, self, C4> xyyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYYY, self, C4> xyyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXXX, self, C4> yxxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXXY, self, C4> yxxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXYX, self, C4> yxyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXYY, self, C4> yxyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYXX, self, C4> yyxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYXY, self, C4> yyxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYYX, self, C4> yyyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYYY, self, C4> yyyy; \

#define SWIZZLE_D3 \
	using self = vector_base <T, 3>; \
	using C1 = scalar <T>;\
	[[no_unique_address]] swizzle_component <Swizzle::eX, self, C1> x; \
	[[no_unique_address]] swizzle_component <Swizzle::eY, self, C1> y; \
	[[no_unique_address]] swizzle_component <Swizzle::eZ, self, C1> z; \
	using C2 = vector <T, 2>;\
	[[no_unique_address]] swizzle_component <Swizzle::eXX, self, C2> xx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXY, self, C2> xy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZ, self, C2> xz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYX, self, C2> yx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYY, self, C2> yy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZ, self, C2> yz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZX, self, C2> zx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZY, self, C2> zy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZ, self, C2> zz; \
	using C3 = vector <T, 3>;\
	[[no_unique_address]] swizzle_component <Swizzle::eXXX, self, C3> xxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXY, self, C3> xxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXZ, self, C3> xxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYX, self, C3> xyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYY, self, C3> xyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYZ, self, C3> xyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZX, self, C3> xzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZY, self, C3> xzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZZ, self, C3> xzz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXX, self, C3> yxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXY, self, C3> yxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXZ, self, C3> yxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYX, self, C3> yyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYY, self, C3> yyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYZ, self, C3> yyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZX, self, C3> yzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZY, self, C3> yzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZZ, self, C3> yzz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXX, self, C3> zxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXY, self, C3> zxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXZ, self, C3> zxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYX, self, C3> zyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYY, self, C3> zyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYZ, self, C3> zyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZX, self, C3> zzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZY, self, C3> zzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZZ, self, C3> zzz; \
	using C4 = vector <T, 4>;\
	[[no_unique_address]] swizzle_component <Swizzle::eXXXX, self, C4> xxxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXXY, self, C4> xxxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXXZ, self, C4> xxxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXYX, self, C4> xxyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXYY, self, C4> xxyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXYZ, self, C4> xxyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXZX, self, C4> xxzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXZY, self, C4> xxzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXZZ, self, C4> xxzz; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYXX, self, C4> xyxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYXY, self, C4> xyxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYXZ, self, C4> xyxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYYX, self, C4> xyyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYYY, self, C4> xyyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYYZ, self, C4> xyyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYZX, self, C4> xyzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYZY, self, C4> xyzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYZZ, self, C4> xyzz; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZXX, self, C4> xzxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZXY, self, C4> xzxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZXZ, self, C4> xzxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZYX, self, C4> xzyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZYY, self, C4> xzyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZYZ, self, C4> xzyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZZX, self, C4> xzzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZZY, self, C4> xzzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZZZ, self, C4> xzzz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXXX, self, C4> yxxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXXY, self, C4> yxxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXXZ, self, C4> yxxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXYX, self, C4> yxyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXYY, self, C4> yxyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXYZ, self, C4> yxyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXZX, self, C4> yxzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXZY, self, C4> yxzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXZZ, self, C4> yxzz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYXX, self, C4> yyxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYXY, self, C4> yyxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYXZ, self, C4> yyxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYYX, self, C4> yyyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYYY, self, C4> yyyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYYZ, self, C4> yyyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYZX, self, C4> yyzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYZY, self, C4> yyzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYZZ, self, C4> yyzz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZXX, self, C4> yzxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZXY, self, C4> yzxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZXZ, self, C4> yzxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZYX, self, C4> yzyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZYY, self, C4> yzyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZYZ, self, C4> yzyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZZX, self, C4> yzzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZZY, self, C4> yzzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZZZ, self, C4> yzzz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXXX, self, C4> zxxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXXY, self, C4> zxxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXXZ, self, C4> zxxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXYX, self, C4> zxyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXYY, self, C4> zxyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXYZ, self, C4> zxyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXZX, self, C4> zxzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXZY, self, C4> zxzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXZZ, self, C4> zxzz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYXX, self, C4> zyxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYXY, self, C4> zyxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYXZ, self, C4> zyxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYYX, self, C4> zyyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYYY, self, C4> zyyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYYZ, self, C4> zyyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYZX, self, C4> zyzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYZY, self, C4> zyzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYZZ, self, C4> zyzz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZXX, self, C4> zzxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZXY, self, C4> zzxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZXZ, self, C4> zzxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZYX, self, C4> zzyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZYY, self, C4> zzyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZYZ, self, C4> zzyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZZX, self, C4> zzzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZZY, self, C4> zzzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZZZ, self, C4> zzzz; \

#define SWIZZLE_D4 \
	using self = vector_base <T, 4>; \
	using C1 = scalar <T>;\
	[[no_unique_address]] swizzle_component <Swizzle::eX, self, C1> x; \
	[[no_unique_address]] swizzle_component <Swizzle::eY, self, C1> y; \
	[[no_unique_address]] swizzle_component <Swizzle::eZ, self, C1> z; \
	[[no_unique_address]] swizzle_component <Swizzle::eW, self, C1> w; \
	using C2 = vector <T, 2>;\
	[[no_unique_address]] swizzle_component <Swizzle::eXX, self, C2> xx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXY, self, C2> xy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZ, self, C2> xz; \
	[[no_unique_address]] swizzle_component <Swizzle::eXW, self, C2> xw; \
	[[no_unique_address]] swizzle_component <Swizzle::eYX, self, C2> yx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYY, self, C2> yy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZ, self, C2> yz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYW, self, C2> yw; \
	[[no_unique_address]] swizzle_component <Swizzle::eZX, self, C2> zx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZY, self, C2> zy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZ, self, C2> zz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZW, self, C2> zw; \
	[[no_unique_address]] swizzle_component <Swizzle::eWX, self, C2> wx; \
	[[no_unique_address]] swizzle_component <Swizzle::eWY, self, C2> wy; \
	[[no_unique_address]] swizzle_component <Swizzle::eWZ, self, C2> wz; \
	[[no_unique_address]] swizzle_component <Swizzle::eWW, self, C2> ww; \
	using C3 = vector <T, 3>;\
	[[no_unique_address]] swizzle_component <Swizzle::eXXX, self, C3> xxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXY, self, C3> xxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXZ, self, C3> xxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXW, self, C3> xxw; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYX, self, C3> xyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYY, self, C3> xyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYZ, self, C3> xyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYW, self, C3> xyw; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZX, self, C3> xzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZY, self, C3> xzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZZ, self, C3> xzz; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZW, self, C3> xzw; \
	[[no_unique_address]] swizzle_component <Swizzle::eXWX, self, C3> xwx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXWY, self, C3> xwy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXWZ, self, C3> xwz; \
	[[no_unique_address]] swizzle_component <Swizzle::eXWW, self, C3> xww; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXX, self, C3> yxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXY, self, C3> yxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXZ, self, C3> yxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXW, self, C3> yxw; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYX, self, C3> yyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYY, self, C3> yyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYZ, self, C3> yyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYW, self, C3> yyw; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZX, self, C3> yzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZY, self, C3> yzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZZ, self, C3> yzz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZW, self, C3> yzw; \
	[[no_unique_address]] swizzle_component <Swizzle::eYWX, self, C3> ywx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYWY, self, C3> ywy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYWZ, self, C3> ywz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYWW, self, C3> yww; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXX, self, C3> zxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXY, self, C3> zxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXZ, self, C3> zxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXW, self, C3> zxw; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYX, self, C3> zyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYY, self, C3> zyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYZ, self, C3> zyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYW, self, C3> zyw; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZX, self, C3> zzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZY, self, C3> zzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZZ, self, C3> zzz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZW, self, C3> zzw; \
	[[no_unique_address]] swizzle_component <Swizzle::eZWX, self, C3> zwx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZWY, self, C3> zwy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZWZ, self, C3> zwz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZWW, self, C3> zww; \
	[[no_unique_address]] swizzle_component <Swizzle::eWXX, self, C3> wxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eWXY, self, C3> wxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eWXZ, self, C3> wxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eWXW, self, C3> wxw; \
	[[no_unique_address]] swizzle_component <Swizzle::eWYX, self, C3> wyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eWYY, self, C3> wyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eWYZ, self, C3> wyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eWYW, self, C3> wyw; \
	[[no_unique_address]] swizzle_component <Swizzle::eWZX, self, C3> wzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eWZY, self, C3> wzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eWZZ, self, C3> wzz; \
	[[no_unique_address]] swizzle_component <Swizzle::eWZW, self, C3> wzw; \
	[[no_unique_address]] swizzle_component <Swizzle::eWWX, self, C3> wwx; \
	[[no_unique_address]] swizzle_component <Swizzle::eWWY, self, C3> wwy; \
	[[no_unique_address]] swizzle_component <Swizzle::eWWZ, self, C3> wwz; \
	[[no_unique_address]] swizzle_component <Swizzle::eWWW, self, C3> www; \
	using C4 = vector <T, 4>;\
	[[no_unique_address]] swizzle_component <Swizzle::eXXXX, self, C4> xxxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXXY, self, C4> xxxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXXZ, self, C4> xxxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXXW, self, C4> xxxw; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXYX, self, C4> xxyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXYY, self, C4> xxyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXYZ, self, C4> xxyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXYW, self, C4> xxyw; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXZX, self, C4> xxzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXZY, self, C4> xxzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXZZ, self, C4> xxzz; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXZW, self, C4> xxzw; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXWX, self, C4> xxwx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXWY, self, C4> xxwy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXWZ, self, C4> xxwz; \
	[[no_unique_address]] swizzle_component <Swizzle::eXXWW, self, C4> xxww; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYXX, self, C4> xyxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYXY, self, C4> xyxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYXZ, self, C4> xyxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYXW, self, C4> xyxw; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYYX, self, C4> xyyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYYY, self, C4> xyyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYYZ, self, C4> xyyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYYW, self, C4> xyyw; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYZX, self, C4> xyzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYZY, self, C4> xyzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYZZ, self, C4> xyzz; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYZW, self, C4> xyzw; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYWX, self, C4> xywx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYWY, self, C4> xywy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYWZ, self, C4> xywz; \
	[[no_unique_address]] swizzle_component <Swizzle::eXYWW, self, C4> xyww; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZXX, self, C4> xzxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZXY, self, C4> xzxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZXZ, self, C4> xzxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZXW, self, C4> xzxw; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZYX, self, C4> xzyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZYY, self, C4> xzyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZYZ, self, C4> xzyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZYW, self, C4> xzyw; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZZX, self, C4> xzzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZZY, self, C4> xzzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZZZ, self, C4> xzzz; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZZW, self, C4> xzzw; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZWX, self, C4> xzwx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZWY, self, C4> xzwy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZWZ, self, C4> xzwz; \
	[[no_unique_address]] swizzle_component <Swizzle::eXZWW, self, C4> xzww; \
	[[no_unique_address]] swizzle_component <Swizzle::eXWXX, self, C4> xwxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXWXY, self, C4> xwxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXWXZ, self, C4> xwxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eXWXW, self, C4> xwxw; \
	[[no_unique_address]] swizzle_component <Swizzle::eXWYX, self, C4> xwyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXWYY, self, C4> xwyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXWYZ, self, C4> xwyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eXWYW, self, C4> xwyw; \
	[[no_unique_address]] swizzle_component <Swizzle::eXWZX, self, C4> xwzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXWZY, self, C4> xwzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXWZZ, self, C4> xwzz; \
	[[no_unique_address]] swizzle_component <Swizzle::eXWZW, self, C4> xwzw; \
	[[no_unique_address]] swizzle_component <Swizzle::eXWWX, self, C4> xwwx; \
	[[no_unique_address]] swizzle_component <Swizzle::eXWWY, self, C4> xwwy; \
	[[no_unique_address]] swizzle_component <Swizzle::eXWWZ, self, C4> xwwz; \
	[[no_unique_address]] swizzle_component <Swizzle::eXWWW, self, C4> xwww; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXXX, self, C4> yxxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXXY, self, C4> yxxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXXZ, self, C4> yxxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXXW, self, C4> yxxw; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXYX, self, C4> yxyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXYY, self, C4> yxyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXYZ, self, C4> yxyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXYW, self, C4> yxyw; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXZX, self, C4> yxzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXZY, self, C4> yxzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXZZ, self, C4> yxzz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXZW, self, C4> yxzw; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXWX, self, C4> yxwx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXWY, self, C4> yxwy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXWZ, self, C4> yxwz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYXWW, self, C4> yxww; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYXX, self, C4> yyxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYXY, self, C4> yyxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYXZ, self, C4> yyxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYXW, self, C4> yyxw; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYYX, self, C4> yyyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYYY, self, C4> yyyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYYZ, self, C4> yyyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYYW, self, C4> yyyw; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYZX, self, C4> yyzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYZY, self, C4> yyzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYZZ, self, C4> yyzz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYZW, self, C4> yyzw; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYWX, self, C4> yywx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYWY, self, C4> yywy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYWZ, self, C4> yywz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYYWW, self, C4> yyww; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZXX, self, C4> yzxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZXY, self, C4> yzxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZXZ, self, C4> yzxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZXW, self, C4> yzxw; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZYX, self, C4> yzyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZYY, self, C4> yzyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZYZ, self, C4> yzyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZYW, self, C4> yzyw; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZZX, self, C4> yzzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZZY, self, C4> yzzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZZZ, self, C4> yzzz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZZW, self, C4> yzzw; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZWX, self, C4> yzwx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZWY, self, C4> yzwy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZWZ, self, C4> yzwz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYZWW, self, C4> yzww; \
	[[no_unique_address]] swizzle_component <Swizzle::eYWXX, self, C4> ywxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYWXY, self, C4> ywxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYWXZ, self, C4> ywxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYWXW, self, C4> ywxw; \
	[[no_unique_address]] swizzle_component <Swizzle::eYWYX, self, C4> ywyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYWYY, self, C4> ywyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYWYZ, self, C4> ywyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYWYW, self, C4> ywyw; \
	[[no_unique_address]] swizzle_component <Swizzle::eYWZX, self, C4> ywzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYWZY, self, C4> ywzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYWZZ, self, C4> ywzz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYWZW, self, C4> ywzw; \
	[[no_unique_address]] swizzle_component <Swizzle::eYWWX, self, C4> ywwx; \
	[[no_unique_address]] swizzle_component <Swizzle::eYWWY, self, C4> ywwy; \
	[[no_unique_address]] swizzle_component <Swizzle::eYWWZ, self, C4> ywwz; \
	[[no_unique_address]] swizzle_component <Swizzle::eYWWW, self, C4> ywww; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXXX, self, C4> zxxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXXY, self, C4> zxxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXXZ, self, C4> zxxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXXW, self, C4> zxxw; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXYX, self, C4> zxyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXYY, self, C4> zxyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXYZ, self, C4> zxyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXYW, self, C4> zxyw; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXZX, self, C4> zxzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXZY, self, C4> zxzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXZZ, self, C4> zxzz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXZW, self, C4> zxzw; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXWX, self, C4> zxwx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXWY, self, C4> zxwy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXWZ, self, C4> zxwz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZXWW, self, C4> zxww; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYXX, self, C4> zyxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYXY, self, C4> zyxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYXZ, self, C4> zyxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYXW, self, C4> zyxw; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYYX, self, C4> zyyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYYY, self, C4> zyyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYYZ, self, C4> zyyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYYW, self, C4> zyyw; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYZX, self, C4> zyzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYZY, self, C4> zyzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYZZ, self, C4> zyzz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYZW, self, C4> zyzw; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYWX, self, C4> zywx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYWY, self, C4> zywy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYWZ, self, C4> zywz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZYWW, self, C4> zyww; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZXX, self, C4> zzxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZXY, self, C4> zzxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZXZ, self, C4> zzxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZXW, self, C4> zzxw; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZYX, self, C4> zzyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZYY, self, C4> zzyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZYZ, self, C4> zzyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZYW, self, C4> zzyw; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZZX, self, C4> zzzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZZY, self, C4> zzzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZZZ, self, C4> zzzz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZZW, self, C4> zzzw; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZWX, self, C4> zzwx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZWY, self, C4> zzwy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZWZ, self, C4> zzwz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZZWW, self, C4> zzww; \
	[[no_unique_address]] swizzle_component <Swizzle::eZWXX, self, C4> zwxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZWXY, self, C4> zwxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZWXZ, self, C4> zwxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZWXW, self, C4> zwxw; \
	[[no_unique_address]] swizzle_component <Swizzle::eZWYX, self, C4> zwyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZWYY, self, C4> zwyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZWYZ, self, C4> zwyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZWYW, self, C4> zwyw; \
	[[no_unique_address]] swizzle_component <Swizzle::eZWZX, self, C4> zwzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZWZY, self, C4> zwzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZWZZ, self, C4> zwzz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZWZW, self, C4> zwzw; \
	[[no_unique_address]] swizzle_component <Swizzle::eZWWX, self, C4> zwwx; \
	[[no_unique_address]] swizzle_component <Swizzle::eZWWY, self, C4> zwwy; \
	[[no_unique_address]] swizzle_component <Swizzle::eZWWZ, self, C4> zwwz; \
	[[no_unique_address]] swizzle_component <Swizzle::eZWWW, self, C4> zwww; \
	[[no_unique_address]] swizzle_component <Swizzle::eWXXX, self, C4> wxxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eWXXY, self, C4> wxxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eWXXZ, self, C4> wxxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eWXXW, self, C4> wxxw; \
	[[no_unique_address]] swizzle_component <Swizzle::eWXYX, self, C4> wxyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eWXYY, self, C4> wxyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eWXYZ, self, C4> wxyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eWXYW, self, C4> wxyw; \
	[[no_unique_address]] swizzle_component <Swizzle::eWXZX, self, C4> wxzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eWXZY, self, C4> wxzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eWXZZ, self, C4> wxzz; \
	[[no_unique_address]] swizzle_component <Swizzle::eWXZW, self, C4> wxzw; \
	[[no_unique_address]] swizzle_component <Swizzle::eWXWX, self, C4> wxwx; \
	[[no_unique_address]] swizzle_component <Swizzle::eWXWY, self, C4> wxwy; \
	[[no_unique_address]] swizzle_component <Swizzle::eWXWZ, self, C4> wxwz; \
	[[no_unique_address]] swizzle_component <Swizzle::eWXWW, self, C4> wxww; \
	[[no_unique_address]] swizzle_component <Swizzle::eWYXX, self, C4> wyxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eWYXY, self, C4> wyxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eWYXZ, self, C4> wyxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eWYXW, self, C4> wyxw; \
	[[no_unique_address]] swizzle_component <Swizzle::eWYYX, self, C4> wyyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eWYYY, self, C4> wyyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eWYYZ, self, C4> wyyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eWYYW, self, C4> wyyw; \
	[[no_unique_address]] swizzle_component <Swizzle::eWYZX, self, C4> wyzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eWYZY, self, C4> wyzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eWYZZ, self, C4> wyzz; \
	[[no_unique_address]] swizzle_component <Swizzle::eWYZW, self, C4> wyzw; \
	[[no_unique_address]] swizzle_component <Swizzle::eWYWX, self, C4> wywx; \
	[[no_unique_address]] swizzle_component <Swizzle::eWYWY, self, C4> wywy; \
	[[no_unique_address]] swizzle_component <Swizzle::eWYWZ, self, C4> wywz; \
	[[no_unique_address]] swizzle_component <Swizzle::eWYWW, self, C4> wyww; \
	[[no_unique_address]] swizzle_component <Swizzle::eWZXX, self, C4> wzxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eWZXY, self, C4> wzxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eWZXZ, self, C4> wzxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eWZXW, self, C4> wzxw; \
	[[no_unique_address]] swizzle_component <Swizzle::eWZYX, self, C4> wzyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eWZYY, self, C4> wzyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eWZYZ, self, C4> wzyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eWZYW, self, C4> wzyw; \
	[[no_unique_address]] swizzle_component <Swizzle::eWZZX, self, C4> wzzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eWZZY, self, C4> wzzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eWZZZ, self, C4> wzzz; \
	[[no_unique_address]] swizzle_component <Swizzle::eWZZW, self, C4> wzzw; \
	[[no_unique_address]] swizzle_component <Swizzle::eWZWX, self, C4> wzwx; \
	[[no_unique_address]] swizzle_component <Swizzle::eWZWY, self, C4> wzwy; \
	[[no_unique_address]] swizzle_component <Swizzle::eWZWZ, self, C4> wzwz; \
	[[no_unique_address]] swizzle_component <Swizzle::eWZWW, self, C4> wzww; \
	[[no_unique_address]] swizzle_component <Swizzle::eWWXX, self, C4> wwxx; \
	[[no_unique_address]] swizzle_component <Swizzle::eWWXY, self, C4> wwxy; \
	[[no_unique_address]] swizzle_component <Swizzle::eWWXZ, self, C4> wwxz; \
	[[no_unique_address]] swizzle_component <Swizzle::eWWXW, self, C4> wwxw; \
	[[no_unique_address]] swizzle_component <Swizzle::eWWYX, self, C4> wwyx; \
	[[no_unique_address]] swizzle_component <Swizzle::eWWYY, self, C4> wwyy; \
	[[no_unique_address]] swizzle_component <Swizzle::eWWYZ, self, C4> wwyz; \
	[[no_unique_address]] swizzle_component <Swizzle::eWWYW, self, C4> wwyw; \
	[[no_unique_address]] swizzle_component <Swizzle::eWWZX, self, C4> wwzx; \
	[[no_unique_address]] swizzle_component <Swizzle::eWWZY, self, C4> wwzy; \
	[[no_unique_address]] swizzle_component <Swizzle::eWWZZ, self, C4> wwzz; \
	[[no_unique_address]] swizzle_component <Swizzle::eWWZW, self, C4> wwzw; \
	[[no_unique_address]] swizzle_component <Swizzle::eWWWX, self, C4> wwwx; \
	[[no_unique_address]] swizzle_component <Swizzle::eWWWY, self, C4> wwwy; \
	[[no_unique_address]] swizzle_component <Swizzle::eWWWZ, self, C4> wwwz; \
	[[no_unique_address]] swizzle_component <Swizzle::eWWWW, self, C4> wwww; \
