#pragma once

#include "instruction_enums.hpp"

#define SWIZZLE_D2 \
	using self = vector_base <T, 2>; \
	using C1 = scalar <T>;\
	[[no_unique_address]] swizzle_component <SwizzleCode::eX, self, C1> x; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eY, self, C1> y; \
	using C2 = vector <T, 2>;\
	[[no_unique_address]] swizzle_component <SwizzleCode::eXX, self, C2> xx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXY, self, C2> xy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYX, self, C2> yx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYY, self, C2> yy; \
	using C3 = vector <T, 3>;\
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXX, self, C3> xxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXY, self, C3> xxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYX, self, C3> xyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYY, self, C3> xyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXX, self, C3> yxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXY, self, C3> yxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYX, self, C3> yyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYY, self, C3> yyy; \
	using C4 = vector <T, 4>;\
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXXX, self, C4> xxxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXXY, self, C4> xxxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXYX, self, C4> xxyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXYY, self, C4> xxyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYXX, self, C4> xyxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYXY, self, C4> xyxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYYX, self, C4> xyyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYYY, self, C4> xyyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXXX, self, C4> yxxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXXY, self, C4> yxxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXYX, self, C4> yxyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXYY, self, C4> yxyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYXX, self, C4> yyxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYXY, self, C4> yyxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYYX, self, C4> yyyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYYY, self, C4> yyyy; \

#define SWIZZLE_D3 \
	using self = vector_base <T, 3>; \
	using C1 = scalar <T>;\
	[[no_unique_address]] swizzle_component <SwizzleCode::eX, self, C1> x; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eY, self, C1> y; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZ, self, C1> z; \
	using C2 = vector <T, 2>;\
	[[no_unique_address]] swizzle_component <SwizzleCode::eXX, self, C2> xx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXY, self, C2> xy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZ, self, C2> xz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYX, self, C2> yx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYY, self, C2> yy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZ, self, C2> yz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZX, self, C2> zx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZY, self, C2> zy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZ, self, C2> zz; \
	using C3 = vector <T, 3>;\
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXX, self, C3> xxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXY, self, C3> xxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXZ, self, C3> xxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYX, self, C3> xyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYY, self, C3> xyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYZ, self, C3> xyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZX, self, C3> xzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZY, self, C3> xzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZZ, self, C3> xzz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXX, self, C3> yxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXY, self, C3> yxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXZ, self, C3> yxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYX, self, C3> yyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYY, self, C3> yyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYZ, self, C3> yyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZX, self, C3> yzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZY, self, C3> yzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZZ, self, C3> yzz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXX, self, C3> zxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXY, self, C3> zxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXZ, self, C3> zxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYX, self, C3> zyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYY, self, C3> zyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYZ, self, C3> zyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZX, self, C3> zzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZY, self, C3> zzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZZ, self, C3> zzz; \
	using C4 = vector <T, 4>;\
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXXX, self, C4> xxxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXXY, self, C4> xxxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXXZ, self, C4> xxxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXYX, self, C4> xxyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXYY, self, C4> xxyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXYZ, self, C4> xxyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXZX, self, C4> xxzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXZY, self, C4> xxzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXZZ, self, C4> xxzz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYXX, self, C4> xyxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYXY, self, C4> xyxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYXZ, self, C4> xyxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYYX, self, C4> xyyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYYY, self, C4> xyyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYYZ, self, C4> xyyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYZX, self, C4> xyzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYZY, self, C4> xyzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYZZ, self, C4> xyzz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZXX, self, C4> xzxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZXY, self, C4> xzxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZXZ, self, C4> xzxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZYX, self, C4> xzyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZYY, self, C4> xzyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZYZ, self, C4> xzyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZZX, self, C4> xzzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZZY, self, C4> xzzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZZZ, self, C4> xzzz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXXX, self, C4> yxxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXXY, self, C4> yxxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXXZ, self, C4> yxxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXYX, self, C4> yxyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXYY, self, C4> yxyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXYZ, self, C4> yxyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXZX, self, C4> yxzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXZY, self, C4> yxzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXZZ, self, C4> yxzz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYXX, self, C4> yyxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYXY, self, C4> yyxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYXZ, self, C4> yyxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYYX, self, C4> yyyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYYY, self, C4> yyyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYYZ, self, C4> yyyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYZX, self, C4> yyzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYZY, self, C4> yyzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYZZ, self, C4> yyzz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZXX, self, C4> yzxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZXY, self, C4> yzxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZXZ, self, C4> yzxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZYX, self, C4> yzyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZYY, self, C4> yzyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZYZ, self, C4> yzyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZZX, self, C4> yzzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZZY, self, C4> yzzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZZZ, self, C4> yzzz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXXX, self, C4> zxxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXXY, self, C4> zxxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXXZ, self, C4> zxxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXYX, self, C4> zxyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXYY, self, C4> zxyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXYZ, self, C4> zxyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXZX, self, C4> zxzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXZY, self, C4> zxzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXZZ, self, C4> zxzz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYXX, self, C4> zyxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYXY, self, C4> zyxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYXZ, self, C4> zyxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYYX, self, C4> zyyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYYY, self, C4> zyyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYYZ, self, C4> zyyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYZX, self, C4> zyzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYZY, self, C4> zyzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYZZ, self, C4> zyzz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZXX, self, C4> zzxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZXY, self, C4> zzxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZXZ, self, C4> zzxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZYX, self, C4> zzyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZYY, self, C4> zzyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZYZ, self, C4> zzyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZZX, self, C4> zzzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZZY, self, C4> zzzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZZZ, self, C4> zzzz; \

#define SWIZZLE_D4 \
	using self = vector_base <T, 4>; \
	using C1 = scalar <T>;\
	[[no_unique_address]] swizzle_component <SwizzleCode::eX, self, C1> x; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eY, self, C1> y; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZ, self, C1> z; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eW, self, C1> w; \
	using C2 = vector <T, 2>;\
	[[no_unique_address]] swizzle_component <SwizzleCode::eXX, self, C2> xx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXY, self, C2> xy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZ, self, C2> xz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXW, self, C2> xw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYX, self, C2> yx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYY, self, C2> yy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZ, self, C2> yz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYW, self, C2> yw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZX, self, C2> zx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZY, self, C2> zy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZ, self, C2> zz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZW, self, C2> zw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWX, self, C2> wx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWY, self, C2> wy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWZ, self, C2> wz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWW, self, C2> ww; \
	using C3 = vector <T, 3>;\
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXX, self, C3> xxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXY, self, C3> xxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXZ, self, C3> xxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXW, self, C3> xxw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYX, self, C3> xyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYY, self, C3> xyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYZ, self, C3> xyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYW, self, C3> xyw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZX, self, C3> xzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZY, self, C3> xzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZZ, self, C3> xzz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZW, self, C3> xzw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXWX, self, C3> xwx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXWY, self, C3> xwy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXWZ, self, C3> xwz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXWW, self, C3> xww; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXX, self, C3> yxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXY, self, C3> yxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXZ, self, C3> yxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXW, self, C3> yxw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYX, self, C3> yyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYY, self, C3> yyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYZ, self, C3> yyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYW, self, C3> yyw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZX, self, C3> yzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZY, self, C3> yzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZZ, self, C3> yzz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZW, self, C3> yzw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYWX, self, C3> ywx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYWY, self, C3> ywy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYWZ, self, C3> ywz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYWW, self, C3> yww; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXX, self, C3> zxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXY, self, C3> zxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXZ, self, C3> zxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXW, self, C3> zxw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYX, self, C3> zyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYY, self, C3> zyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYZ, self, C3> zyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYW, self, C3> zyw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZX, self, C3> zzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZY, self, C3> zzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZZ, self, C3> zzz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZW, self, C3> zzw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZWX, self, C3> zwx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZWY, self, C3> zwy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZWZ, self, C3> zwz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZWW, self, C3> zww; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWXX, self, C3> wxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWXY, self, C3> wxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWXZ, self, C3> wxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWXW, self, C3> wxw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWYX, self, C3> wyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWYY, self, C3> wyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWYZ, self, C3> wyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWYW, self, C3> wyw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWZX, self, C3> wzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWZY, self, C3> wzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWZZ, self, C3> wzz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWZW, self, C3> wzw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWWX, self, C3> wwx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWWY, self, C3> wwy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWWZ, self, C3> wwz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWWW, self, C3> www; \
	using C4 = vector <T, 4>;\
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXXX, self, C4> xxxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXXY, self, C4> xxxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXXZ, self, C4> xxxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXXW, self, C4> xxxw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXYX, self, C4> xxyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXYY, self, C4> xxyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXYZ, self, C4> xxyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXYW, self, C4> xxyw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXZX, self, C4> xxzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXZY, self, C4> xxzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXZZ, self, C4> xxzz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXZW, self, C4> xxzw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXWX, self, C4> xxwx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXWY, self, C4> xxwy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXWZ, self, C4> xxwz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXXWW, self, C4> xxww; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYXX, self, C4> xyxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYXY, self, C4> xyxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYXZ, self, C4> xyxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYXW, self, C4> xyxw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYYX, self, C4> xyyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYYY, self, C4> xyyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYYZ, self, C4> xyyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYYW, self, C4> xyyw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYZX, self, C4> xyzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYZY, self, C4> xyzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYZZ, self, C4> xyzz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYZW, self, C4> xyzw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYWX, self, C4> xywx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYWY, self, C4> xywy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYWZ, self, C4> xywz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXYWW, self, C4> xyww; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZXX, self, C4> xzxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZXY, self, C4> xzxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZXZ, self, C4> xzxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZXW, self, C4> xzxw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZYX, self, C4> xzyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZYY, self, C4> xzyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZYZ, self, C4> xzyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZYW, self, C4> xzyw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZZX, self, C4> xzzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZZY, self, C4> xzzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZZZ, self, C4> xzzz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZZW, self, C4> xzzw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZWX, self, C4> xzwx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZWY, self, C4> xzwy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZWZ, self, C4> xzwz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXZWW, self, C4> xzww; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXWXX, self, C4> xwxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXWXY, self, C4> xwxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXWXZ, self, C4> xwxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXWXW, self, C4> xwxw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXWYX, self, C4> xwyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXWYY, self, C4> xwyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXWYZ, self, C4> xwyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXWYW, self, C4> xwyw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXWZX, self, C4> xwzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXWZY, self, C4> xwzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXWZZ, self, C4> xwzz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXWZW, self, C4> xwzw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXWWX, self, C4> xwwx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXWWY, self, C4> xwwy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXWWZ, self, C4> xwwz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eXWWW, self, C4> xwww; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXXX, self, C4> yxxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXXY, self, C4> yxxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXXZ, self, C4> yxxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXXW, self, C4> yxxw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXYX, self, C4> yxyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXYY, self, C4> yxyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXYZ, self, C4> yxyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXYW, self, C4> yxyw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXZX, self, C4> yxzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXZY, self, C4> yxzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXZZ, self, C4> yxzz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXZW, self, C4> yxzw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXWX, self, C4> yxwx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXWY, self, C4> yxwy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXWZ, self, C4> yxwz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYXWW, self, C4> yxww; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYXX, self, C4> yyxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYXY, self, C4> yyxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYXZ, self, C4> yyxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYXW, self, C4> yyxw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYYX, self, C4> yyyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYYY, self, C4> yyyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYYZ, self, C4> yyyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYYW, self, C4> yyyw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYZX, self, C4> yyzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYZY, self, C4> yyzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYZZ, self, C4> yyzz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYZW, self, C4> yyzw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYWX, self, C4> yywx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYWY, self, C4> yywy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYWZ, self, C4> yywz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYYWW, self, C4> yyww; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZXX, self, C4> yzxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZXY, self, C4> yzxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZXZ, self, C4> yzxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZXW, self, C4> yzxw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZYX, self, C4> yzyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZYY, self, C4> yzyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZYZ, self, C4> yzyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZYW, self, C4> yzyw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZZX, self, C4> yzzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZZY, self, C4> yzzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZZZ, self, C4> yzzz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZZW, self, C4> yzzw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZWX, self, C4> yzwx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZWY, self, C4> yzwy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZWZ, self, C4> yzwz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYZWW, self, C4> yzww; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYWXX, self, C4> ywxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYWXY, self, C4> ywxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYWXZ, self, C4> ywxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYWXW, self, C4> ywxw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYWYX, self, C4> ywyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYWYY, self, C4> ywyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYWYZ, self, C4> ywyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYWYW, self, C4> ywyw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYWZX, self, C4> ywzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYWZY, self, C4> ywzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYWZZ, self, C4> ywzz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYWZW, self, C4> ywzw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYWWX, self, C4> ywwx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYWWY, self, C4> ywwy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYWWZ, self, C4> ywwz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eYWWW, self, C4> ywww; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXXX, self, C4> zxxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXXY, self, C4> zxxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXXZ, self, C4> zxxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXXW, self, C4> zxxw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXYX, self, C4> zxyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXYY, self, C4> zxyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXYZ, self, C4> zxyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXYW, self, C4> zxyw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXZX, self, C4> zxzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXZY, self, C4> zxzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXZZ, self, C4> zxzz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXZW, self, C4> zxzw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXWX, self, C4> zxwx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXWY, self, C4> zxwy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXWZ, self, C4> zxwz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZXWW, self, C4> zxww; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYXX, self, C4> zyxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYXY, self, C4> zyxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYXZ, self, C4> zyxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYXW, self, C4> zyxw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYYX, self, C4> zyyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYYY, self, C4> zyyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYYZ, self, C4> zyyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYYW, self, C4> zyyw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYZX, self, C4> zyzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYZY, self, C4> zyzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYZZ, self, C4> zyzz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYZW, self, C4> zyzw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYWX, self, C4> zywx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYWY, self, C4> zywy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYWZ, self, C4> zywz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZYWW, self, C4> zyww; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZXX, self, C4> zzxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZXY, self, C4> zzxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZXZ, self, C4> zzxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZXW, self, C4> zzxw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZYX, self, C4> zzyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZYY, self, C4> zzyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZYZ, self, C4> zzyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZYW, self, C4> zzyw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZZX, self, C4> zzzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZZY, self, C4> zzzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZZZ, self, C4> zzzz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZZW, self, C4> zzzw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZWX, self, C4> zzwx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZWY, self, C4> zzwy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZWZ, self, C4> zzwz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZZWW, self, C4> zzww; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZWXX, self, C4> zwxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZWXY, self, C4> zwxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZWXZ, self, C4> zwxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZWXW, self, C4> zwxw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZWYX, self, C4> zwyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZWYY, self, C4> zwyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZWYZ, self, C4> zwyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZWYW, self, C4> zwyw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZWZX, self, C4> zwzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZWZY, self, C4> zwzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZWZZ, self, C4> zwzz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZWZW, self, C4> zwzw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZWWX, self, C4> zwwx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZWWY, self, C4> zwwy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZWWZ, self, C4> zwwz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eZWWW, self, C4> zwww; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWXXX, self, C4> wxxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWXXY, self, C4> wxxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWXXZ, self, C4> wxxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWXXW, self, C4> wxxw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWXYX, self, C4> wxyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWXYY, self, C4> wxyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWXYZ, self, C4> wxyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWXYW, self, C4> wxyw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWXZX, self, C4> wxzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWXZY, self, C4> wxzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWXZZ, self, C4> wxzz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWXZW, self, C4> wxzw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWXWX, self, C4> wxwx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWXWY, self, C4> wxwy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWXWZ, self, C4> wxwz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWXWW, self, C4> wxww; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWYXX, self, C4> wyxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWYXY, self, C4> wyxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWYXZ, self, C4> wyxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWYXW, self, C4> wyxw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWYYX, self, C4> wyyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWYYY, self, C4> wyyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWYYZ, self, C4> wyyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWYYW, self, C4> wyyw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWYZX, self, C4> wyzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWYZY, self, C4> wyzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWYZZ, self, C4> wyzz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWYZW, self, C4> wyzw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWYWX, self, C4> wywx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWYWY, self, C4> wywy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWYWZ, self, C4> wywz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWYWW, self, C4> wyww; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWZXX, self, C4> wzxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWZXY, self, C4> wzxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWZXZ, self, C4> wzxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWZXW, self, C4> wzxw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWZYX, self, C4> wzyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWZYY, self, C4> wzyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWZYZ, self, C4> wzyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWZYW, self, C4> wzyw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWZZX, self, C4> wzzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWZZY, self, C4> wzzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWZZZ, self, C4> wzzz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWZZW, self, C4> wzzw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWZWX, self, C4> wzwx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWZWY, self, C4> wzwy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWZWZ, self, C4> wzwz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWZWW, self, C4> wzww; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWWXX, self, C4> wwxx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWWXY, self, C4> wwxy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWWXZ, self, C4> wwxz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWWXW, self, C4> wwxw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWWYX, self, C4> wwyx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWWYY, self, C4> wwyy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWWYZ, self, C4> wwyz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWWYW, self, C4> wwyw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWWZX, self, C4> wwzx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWWZY, self, C4> wwzy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWWZZ, self, C4> wwzz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWWZW, self, C4> wwzw; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWWWX, self, C4> wwwx; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWWWY, self, C4> wwwy; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWWWZ, self, C4> wwwz; \
	[[no_unique_address]] swizzle_component <SwizzleCode::eWWWW, self, C4> wwww; \
