#pragma once

#include "dsl/branching.hpp"
#include "dsl/looping.hpp"
#include "meta/combinator/compute.hpp"
#include "meta/combinator/mesh_shading.hpp"
#include "meta/combinator/rasterization.hpp"
#include "meta/pipeline/compute.hpp"
#include "meta/pipeline/mesh_shading.hpp"
#include "meta/commands.hpp"
#include "meta/descriptor.hpp"
#include "meta/function_construction.hpp"
#include "meta/resource_intrinsic.hpp"
#include "meta/resource_translations.hpp"
#include "meta/return_handler.hpp"
#include "rcgp-rhi.hpp"
